//
// Created by Bergen Allison on 19/12/20.
//

#ifndef DATASTRUCTURES_BINARYSEARCHTREE_H
#define DATASTRUCTURES_BINARYSEARCHTREE_H


class BinarySearchTree {
};


#endif //DATASTRUCTURES_BINARYSEARCHTREE_H
